sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t vandiver247/docker-react-test ./client

script:
  - docker run -e CI=true vandiver247/docker-react-test npm run test

after_success:
  - docker build -t vandiver247/multi-client ./client
  - docker build -t vandiver247/multi-nginx ./nginx
  - docker build -t vandiver247/multi-server ./server
  - docker build -t vandiver247/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vandiver247/multi-client
  - docker push vandiver247/multi-nginx
  - docker push vandiver247/multi-server
  - docker push vandiver247/multi-worker
